placeholder code

diff --git a/examples/a8-bluemix b/examples/a8-bluemix
--- a/examples/a8-bluemix
+++ b/examples/a8-bluemix
@@ -284,6 +284,60 @@ if [ "$ACTION" == "create" ]; then
                 --env A8_PROXY=true \
                 ${BLUEMIX_REGISTRY_HOST}/${BLUEMIX_REGISTRY_NAMESPACE}/$GATEWAY_IMAGE
 
+# #################################################################################
+# # Check the deployment progress
+# #################################################################################
+
+# echo -e "Waiting for the container groups to be created:"
+
+# attempt=0
+# _wait=true
+
+# while $_wait; do
+#     # Sleep for 15s
+#     for (( i = 0 ; i < 3 ; i++ )) do
+#         sleep 5s
+#         echo -n "."
+#     done
+
+#     EXISTING_GROUPS=$(bluemix ic groups)
+#     counter=0
+#     for group in ${BOOKINFO_GROUPS[@]}; do
+#         status=$(echo "$EXISTING_GROUPS" | awk -v pattern="$group" '$0 ~ pattern { print $3; exit; }')
+#         case "$status" in
+#             "CREATE_FAILED")
+#             _wait=false
+#         ;;
+
+#         "DELETE_FAILED")
+#             _wait=false
+#         ;;
+
+#         "CREATE_COMPLETE")
+#             ((counter++))
+#         ;;
+#         esac
+#     done
+
+#     if [ "$counter" -eq "${#BOOKINFO_GROUPS[@]}" ]; then
+#         echo -e "\nBookinfo app has been deployed successfully!"
+#         break
+#     fi
+
+#     ((attempt++))
+#     if [ "$attempt" -gt 12 ]; then  # Timeout after 3min
+#         echo -e "\nTimeout waiting for container groups to be created"
+#         echo "Deploying bookinfo app has failed"
+#         exit 1
+#     fi
+
+#     if [[ $_wait = false ]]; then
+#         echo -e "\nDeploying bookinfo app has failed!\n"
+#         echo -e "Getting the status of all container groups...\n"
+#         bluemix ic groups
+#     fi
+# done
+
         echo "Bookinfo app has been deployed successfully"
     else
         for image in ${HELLOWORLD_IMAGES[@]}; do
